org.gradle.jvmargs=-Xmx4G

java_version=21

minecraft_version=1.21.5
minecraft_version_major = 1.21

group=net.wiredtomato
mod_id=waygl
mod_name=WayGL
mod_description=Load Minecraft with wayland
mod_author=WiredTomato
mod_version=1.1.6

license=MIT

fabric_loader_version=0.16.12
fabric_version=0.119.9+1.21.5
flk_version=1.13.2+kotlin.2.1.20
modmenu_version=14.0.0-rc.2

neoforge_version=21.5.66-beta
neoforge_version_range=[21.0.167,)
kff_loader_version_range=[5,)
kff_version=5.7.0
minecraft_version_range=[1.21,)
minecraft_versions=1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5
credits=

neo_form_version=1.21.5-20250325.162830
parchment_minecraft=1.21.4
parchment_version=2025.03.23

yacl_version=3.6.6+1.21.5

kotlin.code.style=official