minecraftVersion=26.1
minecraftVersionMajor=26.1
minecraftVersionRange=[26.1,)
minecraftDeobf=true
neoformVersion=1
neoforgeVersion=26.1.2.43-beta
neoforgeVersionRange=[26.1.0-beta,)
fabricLoaderVersion=0.19.2
fabricVersion=0.147.0+26.1.2
minecraftVersions=26.1,26.1.1,26.1.2

javaVersion=25

modMenuVersion=18.0.0-alpha.8
clothConfigVersion=26.1.154
