minecraftVersion=26.2
minecraftVersionMajor=26.2
minecraftVersionRange=[26.2,)
minecraftDeobf=true
neoformVersion=1
neoforgeVersion=26.2.0.7-beta
neoforgeVersionRange=[26.2.0.7-beta,)
fabricLoaderVersion=0.19.3
fabricVersion=0.153.0+26.2
minecraftVersions=26.2

javaVersion=25

modMenuVersion=20.0.0-beta.4
clothConfigVersion=26.2.155
