modLoader = "javafml" #mandatory
loaderVersion = "${loaderVersionRange}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId = "${modId}" #mandatory
version = "${version}" #mandatory
displayName = "${modName}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional
credits = "${credits}" #optional
authors = "${author}" #optional
description = '''${modDescription}''' #mandatory (Supports multiline text)

[[mixins]]
config = "${modId}.mixins.json"

[[mixins]]
config = "${modId}.neoforge.mixins.json"

[[dependencies.${modId}]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${neoforgeVersionRange}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${modId}]]
modId = "minecraft"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencied.${modId}]]
modId = "cloth_config"
type = "required"
versionRange = "[${clothConfigVersion},)"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${modId}]
#openGLVersion="[3.2,)"
